keys:
  - &servers
    - &server_galapagos age17umps050l2qnz0axplv550025njeq24uv82vpyncyaupk2l5mcas8eekwc
  - &admins
    - &admin_misterio 7088C7421873E0DB97FF17C2245CAB70B4C225E9
creation_rules:
  - path_regex: hosts/servers/galapagos/secrets.yml$
    key_groups:
    - age:
      - *server_galapagos
      pgp:
      - *admin_misterio
